export interface IColorCode {
  hex: string;
  rgb: string;
}

export interface IColorCodeList {
  [index: string]: IColorCode;
}

export const ColorCode: IColorCodeList = {
  TextPrimary: { hex: '#484848', rgb: '72,72,72' },
  TextSecondary: { hex: '#6C6C6C', rgb: '102,102,102' },
  Primary: { hex: '#FF804B', rgb: '255,128,75' },
  Secondary: { hex: '#FFD5C3', rgb: '255,213,195' },
  Light: { hex: '#D3D3D3', rgb: '211,211,211' },
  Dark: { hex: '#1C1C1C', rgb: '28,28,28' },
  White: { hex: '#FFFFFF', rgb: '255,255,255' },
  Black: { hex: '#000000', rgb: '0,0,0' },
  Blue: { hex: '#003F79', rgb: '0,63,121' },
  Red: { hex: '#D72638', rgb: '215,38,56' },
  Green: {hex: '#3B893A', rgb: '59,137,58'},
  Orange: {hex: '#FFB864', rgb: '255,184,100'},
  DarkGrey: {hex: '#E4E4E4', rgb: '228,228,228'},
  LightGrey: {hex: '#F4F4F4', rgb: '244,244,244'},
  BlueGreen: {hex: '#396571', rgb: '57,101,113'}
};

/*
    Color Set below is generated by Chroma.js
    https://vis4.net/palettes/#/10|d|6ed1a8,b5d1bf,ffffe0|ffffe0,e86f00,cb0030|1|1
*/
export const ColorGrade = {
  Grade0: { hex: '#b52b1a', rgb: '181,43,26' },
  Grade1: { hex: '#d67243', rgb: '214,114,67' },
  Grade2: { hex: '#eea66f', rgb: '238,166,111' },
  Grade3: { hex: '#fcd09d', rgb: '252,208,157' },
  Grade4: { hex: '#fff2cd', rgb: '255,242,205' },
  Grade5: { hex: '#f0f1dc', rgb: '240,241,220' },
  Grade6: { hex: '#d3ddcd', rgb: '211,221,205' },
  Grade7: { hex: '#b5d1bf', rgb: '181,209,191' },
  Grade8: { hex: '#95cdb3', rgb: '149,205,179' },
  Grade9: { hex: '#6ed1a8', rgb: '110,209,168' }
};

export const ColorGradeDef = '#E6FFFFFF';
